### ISSUE TITLE
 太牛了

### ISSUE THREAD

**Issue by Hermione4** [gh-xiao/EmbeddedCar#1]
图形识别一次只能识别一种颜色吗大佬

**Comment by gh-xiao** [comment]
具体查看ConnectTransport的sendShapeInfo()，你可以在这里定义你需要的图形数据，在ShapeDetector类里面，我使用的是HashMap<颜色,HashMap<形状,数量>>，分类了所属颜色的图形统计数据。你可以通过getColorCounts()方法获得指定颜色的所有图形的统计数据。所有相关代码都有注释，自己运行一下就知道了。
